# Display hunk diff
bind -r g display-popup -d '#{pane_current_path}' -w98% -h98% -E hunk diff
# Run Claude Code in a separate session
bind -r a run-shell '\
  DIR="$HOME/workspace/alyn"; \
  SESSION="agent-pi-alyn"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "$DIR" "pi"; \
  tmux display-popup -w68% -h95% -E "tmux attach-session -t $SESSION"'
# Open current directory in nvim
bind -r v new-window -c '#{pane_current_path}' -n nvim "nvim ."
bind -r V display-popup -d '#{pane_current_path}' -w95% -h95% -E "bash -lc 'fzf --preview \"bat --style=numbers --color=always {}\"'"


